### ISSUE TITLE
Any chance to porting it to Godot 4.1?

### ISSUE THREAD

**Issue by carlospazuzu** [joshnajera/godot-vim#4]
Godot 4.1 was lanched these days, I downloaded this awesome addon but it doesn't seem it work at this environment. Any chances for it to work on godot 4.1 ?

**Comment by wrightwriter** [comment]
works for me? although some stuff is broken, not sure if it worked before.

**Comment by carlospazuzu** [comment]
I downloaded the addon from marketplace and it doesn't work. Should I do something or it is supposed to worked right after install?

**Comment by wrightwriter** [comment]
It just worked for me! instantly, no restart or anything. You have to enable the plug in project settings, maybe that's the issue.

**Comment by carlospazuzu** [comment]
That was exactly the issue, my bad!
